create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade,
  title text not null check (char_length(trim(title)) > 0),
  date date not null,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.session_participants (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  unique (session_id, user_id)
);

create table if not exists public.speakers (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  role text not null check (role in ('Speaker', 'Evaluator', 'Table Topics')),
  min_time integer not null check (min_time >= 0),
  max_time integer not null check (max_time >= min_time),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  speaker_id bigint not null references public.speakers(id) on delete cascade,
  content_score integer not null check (content_score between 1 and 10),
  delivery_score integer not null check (delivery_score between 1 and 10),
  confidence_score integer not null check (confidence_score between 1 and 10),
  comment text,
  created_at timestamp with time zone not null default now()
);

alter table public.sessions add column if not exists user_id uuid references public.users(id) on delete cascade;

insert into public.session_participants (session_id, user_id)
select public.sessions.id, public.sessions.user_id
from public.sessions
where public.sessions.user_id is not null
on conflict (session_id, user_id) do nothing;

create or replace function public.handle_new_session_participant()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.user_id is not null then
    insert into public.session_participants (session_id, user_id)
    values (new.id, new.user_id)
    on conflict (session_id, user_id) do nothing;
  end if;

  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (id, email, display_name)
  values (
    new.id,
    new.email,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'display_name', '')), '')
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = coalesce(excluded.display_name, public.users.display_name);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

drop trigger if exists on_session_created_add_participant on public.sessions;
create trigger on_session_created_add_participant
after insert on public.sessions
for each row execute procedure public.handle_new_session_participant();

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.session_participants enable row level security;
alter table public.speakers enable row level security;
alter table public.feedback enable row level security;

create index if not exists sessions_user_id_idx on public.sessions (user_id);
create index if not exists session_participants_session_id_idx on public.session_participants (session_id);
create index if not exists session_participants_user_id_idx on public.session_participants (user_id);
create index if not exists speakers_session_id_idx on public.speakers (session_id);
create index if not exists feedback_speaker_id_idx on public.feedback (speaker_id);

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
on public.users
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can read own sessions" on public.sessions;
create policy "Users can read related sessions"
on public.sessions
for select
to authenticated
using (
  auth.uid() = user_id or exists (
    select 1
    from public.session_participants
    where public.session_participants.session_id = public.sessions.id
      and public.session_participants.user_id = auth.uid()
  )
);

drop policy if exists "Users can insert own sessions" on public.sessions;
create policy "Users can insert own sessions"
on public.sessions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own sessions" on public.sessions;
create policy "Users can update own sessions"
on public.sessions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own sessions" on public.sessions;
create policy "Users can delete own sessions"
on public.sessions
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read related session participants" on public.session_participants;
create policy "Users can read related session participants"
on public.session_participants
for select
to authenticated
using (
  auth.uid() = user_id or exists (
    select 1
    from public.sessions
    where public.sessions.id = public.session_participants.session_id
      and (
        public.sessions.user_id = auth.uid() or exists (
          select 1
          from public.session_participants as membership
          where membership.session_id = public.session_participants.session_id
            and membership.user_id = auth.uid()
        )
      )
  )
);

drop policy if exists "Users can insert self into owned sessions" on public.session_participants;
create policy "Users can insert self into owned sessions"
on public.session_participants
for insert
to authenticated
with check (
  auth.uid() = user_id and exists (
    select 1
    from public.sessions
    where public.sessions.id = public.session_participants.session_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete related session participants" on public.session_participants;
create policy "Users can delete related session participants"
on public.session_participants
for delete
to authenticated
using (
  auth.uid() = user_id or exists (
    select 1
    from public.sessions
    where public.sessions.id = public.session_participants.session_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can read related speakers" on public.speakers;
create policy "Users can read related speakers"
on public.speakers
for select
to authenticated
using (
  exists (
    select 1
    from public.sessions
    where public.sessions.id = public.speakers.session_id and (
      public.sessions.user_id = auth.uid() or exists (
        select 1
        from public.session_participants
        where public.session_participants.session_id = public.sessions.id
          and public.session_participants.user_id = auth.uid()
      )
    )
  )
);

drop policy if exists "Users can insert own speakers" on public.speakers;
create policy "Users can insert own speakers"
on public.speakers
for insert
to authenticated
with check (
  exists (
    select 1
    from public.sessions
    where public.sessions.id = public.speakers.session_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can update own speakers" on public.speakers;
create policy "Users can update own speakers"
on public.speakers
for update
to authenticated
using (
  exists (
    select 1
    from public.sessions
    where public.sessions.id = public.speakers.session_id
      and public.sessions.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.sessions
    where public.sessions.id = public.speakers.session_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete own speakers" on public.speakers;
create policy "Users can delete own speakers"
on public.speakers
for delete
to authenticated
using (
  exists (
    select 1
    from public.sessions
    where public.sessions.id = public.speakers.session_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can read related feedback" on public.feedback;
create policy "Users can read related feedback"
on public.feedback
for select
to authenticated
using (
  exists (
    select 1
    from public.speakers
    join public.sessions on public.sessions.id = public.speakers.session_id
    where public.speakers.id = public.feedback.speaker_id
      and (
        public.sessions.user_id = auth.uid() or exists (
          select 1
          from public.session_participants
          where public.session_participants.session_id = public.sessions.id
            and public.session_participants.user_id = auth.uid()
        )
      )
  )
);

drop policy if exists "Users can insert own feedback" on public.feedback;
create policy "Users can insert own feedback"
on public.feedback
for insert
to authenticated
with check (
  exists (
    select 1
    from public.speakers
    join public.sessions on public.sessions.id = public.speakers.session_id
    where public.speakers.id = public.feedback.speaker_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can update own feedback" on public.feedback;
create policy "Users can update own feedback"
on public.feedback
for update
to authenticated
using (
  exists (
    select 1
    from public.speakers
    join public.sessions on public.sessions.id = public.speakers.session_id
    where public.speakers.id = public.feedback.speaker_id
      and public.sessions.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.speakers
    join public.sessions on public.sessions.id = public.speakers.session_id
    where public.speakers.id = public.feedback.speaker_id
      and public.sessions.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete own feedback" on public.feedback;
create policy "Users can delete own feedback"
on public.feedback
for delete
to authenticated
using (
  exists (
    select 1
    from public.speakers
    join public.sessions on public.sessions.id = public.speakers.session_id
    where public.speakers.id = public.feedback.speaker_id
      and public.sessions.user_id = auth.uid()
  )
);