create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  date date not null,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.speakers (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  role text not null check (role in ('Speaker', 'Evaluator', 'Table Topics')),
  min_time integer not null check (min_time >= 0),
  max_time integer not null check (max_time >= min_time),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  speaker_id bigint not null references public.speakers(id) on delete cascade,
  content_score integer not null check (content_score between 1 and 10),
  delivery_score integer not null check (delivery_score between 1 and 10),
  confidence_score integer not null check (confidence_score between 1 and 10),
  comment text,
  created_at timestamp with time zone not null default now()
);

alter table public.sessions enable row level security;
alter table public.speakers enable row level security;
alter table public.feedback enable row level security;

drop policy if exists "Allow public read on sessions" on public.sessions;
create policy "Allow public read on sessions"
on public.sessions
for select
to anon
using (true);

drop policy if exists "Allow public insert on sessions" on public.sessions;
create policy "Allow public insert on sessions"
on public.sessions
for insert
to anon
with check (true);

drop policy if exists "Allow public read on speakers" on public.speakers;
create policy "Allow public read on speakers"
on public.speakers
for select
to anon
using (true);

drop policy if exists "Allow public insert on speakers" on public.speakers;
create policy "Allow public insert on speakers"
on public.speakers
for insert
to anon
with check (true);

drop policy if exists "Allow public read on feedback" on public.feedback;
create policy "Allow public read on feedback"
on public.feedback
for select
to anon
using (true);

drop policy if exists "Allow public insert on feedback" on public.feedback;
create policy "Allow public insert on feedback"
on public.feedback
for insert
to anon
with check (true);